name: Backend Tests

on:
  push:
    branches: [ "*" ]
    paths: [ "backend/**" ]
  pull_request:
    branches: [ "*" ]
    paths: [ "backend/**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17.0.5
          cache: 'sbt'
      - name: Build and Test with Coverage
        working-directory: ./backend
        run: sbt clean coverage test coverageReport
      - name: Publish coverage to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/scoverage-report

